name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NODE_VERSION: '18.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
          NEXT_PUBLIC_AZURE_AD_B2C_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_AZURE_AD_B2C_CLIENT_ID }}
          NEXT_PUBLIC_AZURE_AD_B2C_TENANT_NAME: ${{ secrets.NEXT_PUBLIC_AZURE_AD_B2C_TENANT_NAME }}
          NEXT_PUBLIC_AZURE_AD_B2C_DOMAIN: ${{ secrets.NEXT_PUBLIC_AZURE_AD_B2C_DOMAIN }}
          NEXT_PUBLIC_AZURE_AD_B2C_PRIMARY_USER_FLOW: ${{ secrets.NEXT_PUBLIC_AZURE_AD_B2C_PRIMARY_USER_FLOW }}

      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
        working-directory: ./frontend

      - name: Get Deployment URL
        id: get-url
        run: |
          URL=$(cat frontend/deployment-url.txt)
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: 'Deployment Success Notification'
        if: success()
        run: |
          echo "::notice::✅ Frontend deployed successfully to Vercel"
          echo "::notice::🔗 Deployment URL: ${{ steps.get-url.outputs.url }}"

      - name: 'Deployment Failure Notification'
        if: failure()
        run: |
          echo "::error::❌ Frontend deployment failed"
          echo "::error::Check logs above for details"

